source "http://rubygems.org"
source "http://rubygems.org"
source "http://gems.rubyforge.org"
source "http://gems.rubyonrails.org"
source "http://gems.github.com"
source "http://gemcutter.org"

gem "addressable", "2.2.5"
gem "bcrypt-ruby", "2.1.4"
gem "bundler", ">= 1.0.7"
gem "configuration", "1.2.0"
gem "data_mapper", "1.1.0"
gem "data_objects", "0.10.5"
gem "dm-aggregates", "1.1.0"
gem "dm-constraints", "1.1.0"
gem "dm-core", "1.1.0"
gem "dm-do-adapter", "1.1.0"
gem "dm-migrations", "1.1.0"
gem "dm-mysql-adapter", "1.1.0"
gem "dm-serializer", "1.1.0"
gem "dm-sqlite-adapter", "1.1.0"
gem "dm-timestamps", "1.1.0"
gem "dm-transactions", "1.1.0"
gem "dm-types", "1.1.0"
gem "dm-validations", "1.1.0"
gem "do_mysql", "0.10.5"
gem "do_sqlite3", "0.10.5"
gem "fastercsv", "1.5.4"
gem "heroku", "2.1.4"
gem "json", "1.4.6"
gem "launchy", "0.4.0"
gem "mime-types", "1.16"
gem "mysql", "2.8.1"
gem "rack", "1.2.2"
gem "rake", "0.8.7"
gem "rest-client", "1.6.1"
gem "sinatra", "1.2.6"
gem "sqlite3", "1.3.3"
gem "sqlite3-ruby", "1.3.3"
gem "stringex", "1.2.1"
gem "term-ansicolor", "1.0.5"
gem "tilt", "1.3"
gem "uuidtools", "2.1.2"
